version: '3.1'

services:
  srvmongo:
    image: mongo:4.2-bionic
    ports:
        - 37017:27017
    volumes: 
      - /data/db/smartgas:/data/db
    tty: true
    stdin_open: true
    container_name: ctn_srvmongo
  srvaccs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APPNAME=srvaccounts
    ports:
      - 80:8080
    tty: true
    stdin_open: true
    entrypoint: ["/usr/bin/eensy/srvaccounts"]
    container_name: ctn_srvaccs

    links:
      - srvmongo